RtmpServer:
  ClusterCnf: ["127.0.0.1:1935","10.137.16.47:1935"]
  SelfIp: "127.0.0.1:1935"
  RtmpListen: [":1935","/tmp/rtmp.socket8"]
  HttpListen: [":8087","/tmp/http.socket6"]
  QuicListen: ":443"
  KcpListen: ":9997"
  
UserConf:
  PublishDomain:
    test.uplive.com:
      UniqueName: test
      App:
        live:
          GopCacheNum: 2
          ExtTimeSend: 1
          RecodeFlv: 1
          RecodeHls: 1
          hlsFragment: "5s"
          RecodeFlvPath: "/dev/shm/data/flv"
          RecodeHlsPath: "/data/hls"
          RecodePicture: 1
          TurnHost: ["test.uplive.com/test"]
        test:
          GopCacheNum: 1
          RecodeHls: 1
          hlsFragment: "5s"
          RecodeFlvPath: "/dev/shm/data/flv"
          RecodeHlsPath: "/data/hls"
          RecodePicture: 1
        test1:
          GopCacheNum: 1
          RecodeFlv: 1
          RecodeHls: 1
          hlsFragment: "5s"
          RecodeFlvPath: "/data/flv"
          RecodeHlsPath: "/data/hls"
          RecodePicture: 1
  PlayDomain:
    test.live.com:
      UniqueName: test
      App:
        live:

